# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmgDkOH0bK9D3irNndDdveqgwPqSHuZ9
"""

import streamlit as st
st.write('Hello,*World*:sunglasses:')